#!/usr/bin/env python3
"""Generate reproducible evaluation cases from the shipped dictionary.

Hand-written cases (tests/cases/*.tsv) say what the brief asks for; these
generated ones say how the matcher behaves across a few hundred words we did
not choose, which is what makes the accuracy numbers in EVALUATION.md mean
anything.  The seed is fixed, so re-running this produces the same file.

Usage:
    python3 scripts/make_testset.py [--typos N] [--skeletons N] [--seed S]
"""

from __future__ import annotations

import argparse
import random
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _common import REPO, skeleton, write_text  # noqa: E402

CASES = REPO / "tests" / "cases"
KEYBOARD_ROWS = ["qwertyuiop", "asdfghjkl", "zxcvbnm"]


def neighbours() -> dict[str, list[str]]:
    """QWERTY adjacency, mirroring rime/lua/spellless/distance.lua."""
    keys = []
    for row, (letters, x0) in enumerate(zip(KEYBOARD_ROWS, (0.0, 0.25, 0.75))):
        for i, ch in enumerate(letters):
            keys.append((ch, x0 + i, row))
    out: dict[str, list[str]] = {c: [] for c, _, _ in keys}
    for a, ax, ay in keys:
        for b, bx, by in keys:
            if a != b and abs(ay - by) <= 1 and abs(ax - bx) <= 1.0:
                out[a].append(b)
    return out


NEIGHBOURS = neighbours()


def corrupt(word: str, rng: random.Random) -> tuple[str, str]:
    """Apply one plausible fast-typing slip.  Returns (typo, kind)."""
    kinds = ["transpose", "delete", "insert", "substitute"]
    for _ in range(20):
        kind = rng.choice(kinds)
        if kind == "transpose" and len(word) >= 3:
            i = rng.randrange(len(word) - 1)
            if word[i] == word[i + 1]:
                continue
            return word[:i] + word[i + 1] + word[i] + word[i + 2:], kind
        if kind == "delete" and len(word) >= 4:
            i = rng.randrange(1, len(word))
            return word[:i] + word[i + 1:], kind
        if kind == "insert":
            i = rng.randrange(1, len(word) + 1)
            return word[:i] + word[i - 1] + word[i:], kind  # doubled letter
        if kind == "substitute" and len(word) >= 3:
            i = rng.randrange(1, len(word))
            opts = NEIGHBOURS.get(word[i])
            if not opts:
                continue
            return word[:i] + rng.choice(opts) + word[i + 1:], kind
    return word, "none"


def load_words() -> list[str]:
    path = REPO / "generated" / "spellless.words"
    if not path.exists():
        raise SystemExit("run scripts/build_dictionary.py first")
    return path.read_text(encoding="utf-8").split("\n")[:-1]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--typos", type=int, default=500)
    ap.add_argument("--skeletons", type=int, default=400)
    ap.add_argument("--seed", type=int, default=20260904)
    # Words this common are what people actually type; going deeper into the
    # tail measures the corpus, not the matcher.
    ap.add_argument("--from-rank", type=int, default=150)
    ap.add_argument("--to-rank", type=int, default=12000)
    args = ap.parse_args()

    words = load_words()
    vocabulary = set(words)
    pool = words[args.from_rank - 1: args.to_rank]
    rng = random.Random(args.seed)

    typo_lines, seen = [], set()
    candidates = [w for w in pool if len(w) >= 4 and w.isalpha()]
    rng.shuffle(candidates)
    for word in candidates:
        if len(typo_lines) >= args.typos:
            break
        typo, kind = corrupt(word, rng)
        # A "typo" that is itself a word is a different question (see
        # tests/cases/ambiguity.tsv), so leave those out of the accuracy set.
        if kind == "none" or typo == word or typo in vocabulary or typo in seen:
            continue
        seen.add(typo)
        typo_lines.append(f"{typo}\t{word}\t5\t{kind}")

    skel_lines, seen = [], set()
    candidates = [w for w in pool if len(w) >= 6 and w.isalpha()]
    rng.shuffle(candidates)
    for word in candidates:
        if len(skel_lines) >= args.skeletons:
            break
        s = skeleton(word)
        # Skip skeletons that are ordinary words: those inputs are exact
        # matches first and abbreviations second, which is the right behaviour
        # but not what this file is measuring.
        if len(s) < 4 or s in vocabulary or s in seen:
            continue
        seen.add(s)
        skel_lines.append(f"{s}\t{word}\t5\tlen{min(len(s), 9)}")

    header = ("# Generated by scripts/make_testset.py -- do not edit by hand.\n"
              f"# seed={args.seed} ranks {args.from_rank}..{args.to_rank}\n"
              "# input <TAB> expected <TAB> max_rank <TAB> group\n")
    write_text(CASES / "generated_typos.tsv", header + "\n".join(typo_lines) + "\n")
    write_text(CASES / "generated_skeletons.tsv", header + "\n".join(skel_lines) + "\n")
    print(f"done: {len(typo_lines)} typo cases, {len(skel_lines)} skeleton cases")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
