#!/usr/bin/env python3
"""Build the release archives.

    python3 scripts/package.py --version 0.1.0
    python3 scripts/package.py --version 0.1.0 --weasel ../spellless-weasel

Two products, because they answer two different questions.

**`spellless-<version>.zip`** is the schema on its own: the YAML, the Lua, the
generated dictionary and the installer.  It drops into a Rime frontend that is
already installed and works on every platform Rime does, because everything in
it is data and Lua.  The one requirement is that the frontend carry
librime-lua, and the official builds of Weasel, Squirrel and the Linux packages
all do -- `rime/librime`'s release workflow builds
`hchunhui/librime-lua lotem/librime-octagram rime/librime-predict` into the
macOS and Windows artefacts that Weasel and Squirrel ship.

**`spellless-weasel-<version>-installer.exe`** is Windows only and is built in
the fork's own tree; `--weasel` stages this repository into it and stops there,
because the installer needs MSVC and NSIS on Windows.  There is no macOS
equivalent and this script will not pretend otherwise: the fork is a fork of
Weasel, which is a Windows text service.  See docs/RELEASING.md.

The version goes into the archive's `version.lua`, so `zzver` in a text box
reports the release rather than a git hash nobody can look up.
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import zipfile
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# What goes in the schema-only archive, relative to the repository root.  The
# layout is deliberately the repository's own: `scripts/install.py` resolves
# its payload relative to itself, so it runs unmodified out of the archive.
CONTENTS = [
    "rime/spellless.schema.yaml",
    "rime/spellless.ico",
    "rime/lua/spellless.lua",
    "rime/lua/spellless/",
    "generated/",
    "scripts/install.py",
    "LICENSE",
]

# Everything a frontend needs at runtime, as (source, destination under the
# frontend's *shared* data directory).  The bundled installer puts Spellless
# where the schemas it ships with live, rather than in the user directory, so
# that a fresh install works before the user has one.
BUNDLE = [
    ("rime/spellless.schema.yaml", "spellless.schema.yaml"),
    ("rime/spellless.ico", "spellless.ico"),
    ("rime/lua/spellless.lua", "lua/spellless.lua"),
    ("rime/lua/spellless/", "lua/spellless/"),
    ("generated/", "spellless/"),
]

VERSION_RE = re.compile(r"^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$")


def git(*args: str) -> str | None:
    try:
        out = subprocess.run(["git", "-C", str(REPO), *args],
                             capture_output=True, text=True, timeout=15)
    except (OSError, subprocess.SubprocessError):
        return None
    return out.stdout.strip() or None if out.returncode == 0 else None


def version_module(version: str) -> str:
    """The `version.lua` the archive ships.

    An installed copy normally gets this written by `install.py` from git.  An
    archive has no git, so it is written here instead and `install.py` leaves a
    real revision alone -- otherwise unpacking a tagged release and installing
    it would report "unknown", which is worse than useless in the one place
    whose entire job is saying what is running.
    """
    built = git("log", "-1", "--format=%cs") or "unknown"
    return (
        "-- Generated by scripts/package.py for a release archive.\n"
        "-- Do not edit; see the copy in the repository for why this is a\n"
        "-- module and not a data file.\n"
        "return {\n"
        f'  revision  = "{version}",\n'
        f'  built     = "{built}",\n'
        "  installed = nil,\n"
        "}\n"
    )


def check_tree(version: str) -> None:
    """Refuse to package something nobody can reproduce."""
    problems = []
    if git("status", "--porcelain"):
        problems.append("the working tree has uncommitted changes")
    for name in ("generated/spellless.words", "generated/spellless.alpha",
                 "generated/spellless.skel", "generated/spellless.forms",
                 "generated/spellless.weights"):
        if not (REPO / name).exists():
            problems.append(f"{name} is missing -- run `make`")
    if not VERSION_RE.match(version):
        problems.append(f"{version!r} is not a version like 1.2.3 or 1.2.3-rc1")
    if problems:
        for p in problems:
            print(f"  refusing: {p}", file=sys.stderr)
        sys.exit(1)


def walk(source: Path) -> list[Path]:
    if source.is_file():
        return [source]
    return sorted(p for p in source.rglob("*") if p.is_file())


def build_zip(version: str, out_dir: Path) -> Path:
    stem = f"spellless-{version}"
    archive = out_dir / f"{stem}.zip"
    out_dir.mkdir(parents=True, exist_ok=True)
    stamp = version_module(version)

    written = 0
    with zipfile.ZipFile(archive, "w", zipfile.ZIP_DEFLATED) as zf:
        for entry in CONTENTS:
            source = REPO / entry
            if not source.exists():
                sys.exit(f"missing from the tree: {entry}")
            for path in walk(source):
                rel = path.relative_to(REPO)
                if rel.as_posix() == "rime/lua/spellless/version.lua":
                    zf.writestr(f"{stem}/{rel.as_posix()}", stamp)
                else:
                    zf.write(path, f"{stem}/{rel.as_posix()}")
                written += 1
        zf.writestr(f"{stem}/README.md", readme(version))
    print(f"  wrote {archive}  ({written + 1} files, "
          f"{archive.stat().st_size / 1e6:.1f} MB)")
    return archive


def readme(version: str) -> str:
    return f"""# Spellless {version}

A fuzzy English input method: type an approximate spelling, pick the word you
meant.  This archive is the schema, the matcher and the dictionary -- it
installs into a Rime frontend you already have.

## What you need first

A Rime frontend **built with librime-lua**, which the official builds all are:

| | |
| --- | --- |
| Windows | [Weasel](https://rime.im/download/) |
| macOS | [Squirrel](https://rime.im/download/) |
| Linux | `ibus-rime` or `fcitx5-rime` from your distribution |

## Install

```
python3 scripts/install.py
```

It finds the Rime user directory itself -- the registry on Windows,
`~/Library/Rime` on macOS, `~/.config/ibus/rime` or
`~/.local/share/fcitx5/rime` on Linux -- copies the payload in, and adds the
schema to `default.custom.yaml` without disturbing the schemas already there.
`--dry-run` shows what it would do, `--user-dir DIR` overrides the search, and
`--uninstall` removes exactly what it wrote.

Then **redeploy the frontend** (its tray or menu-bar icon has the entry;
Chinese builds call it 「重新部署」) and pick Spellless from the schema menu,
usually <kbd>Ctrl</kbd>+<kbd>`</kbd> or <kbd>F4</kbd>.

To check what is actually running, type `zzver` in any text box.  It should say
`spellless {version}`.

## Three things it will not do here

`reclaim_space`, `absorb_fragment` and `word_backspace` -- the features that
edit text already in the document -- need frontend support that stock Rime does
not have, and they ship **off**.  On Windows they are available in the bundled
build; see the project README.

## Licence

MIT.  See LICENSE.
"""


def stage_weasel(version: str, weasel: Path) -> None:
    """Copy the payload into a checkout of the Weasel fork, ready to package.

    Stops short of building.  `build.bat installer` needs MSVC and NSIS on
    Windows, and running it from here would hide which half failed.
    """
    data = weasel / "output" / "data"
    if not data.is_dir():
        sys.exit(f"no {data} -- build the fork first, so output/ exists")

    for src_rel, dst_rel in BUNDLE:
        src, dst = REPO / src_rel, data / dst_rel
        if src.is_dir():
            shutil.rmtree(dst, ignore_errors=True)
            shutil.copytree(src, dst)
        else:
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst)
        print(f"    {src_rel} -> output/data/{dst_rel}")

    stamped = data / "lua" / "spellless" / "version.lua"
    stamped.write_text(version_module(version), encoding="utf-8")
    print(f"    stamped {version} into output/data/lua/spellless/version.lua")

    enable_in_default(data / "default.yaml")


def enable_in_default(path: Path) -> None:
    """Put `spellless` at the top of the bundled default.yaml's schema_list.

    The shipped file rather than a patch: this is the frontend's own default
    list, and a fresh install has no user directory for `default.custom.yaml`
    to live in yet.  First, because somebody installing this build is
    installing it for Spellless.
    """
    text = path.read_text(encoding="utf-8")
    if re.search(r"^\s*-\s*schema:\s*spellless\s*$", text, re.M):
        print("    default.yaml already lists spellless")
        return
    new, n = re.subn(r"(?m)^(schema_list:\s*\n)", r"\1  - schema: spellless\n",
                     text, count=1)
    if n != 1:
        sys.exit(f"could not find schema_list: in {path}")
    path.write_text(new, encoding="utf-8")
    print("    added spellless to output/data/default.yaml")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--version", required=True, help="release version, e.g. 0.1.0")
    ap.add_argument("--out", default="dist", help="where to write (default: dist/)")
    ap.add_argument("--weasel", metavar="DIR",
                    help="also stage into a checkout of the Weasel fork")
    ap.add_argument("--allow-dirty", action="store_true",
                    help="package a tree with uncommitted changes anyway")
    args = ap.parse_args()

    if args.allow_dirty:
        print("packaging a dirty tree, as asked")
    else:
        check_tree(args.version)

    print(f"Spellless {args.version}, from "
          f"{git('describe', '--always', '--dirty', '--exclude', '*') or 'no git'}"
          f" at {datetime.now(timezone.utc):%Y-%m-%d %H:%M} UTC\n")

    print("schema archive:")
    build_zip(args.version, REPO / args.out)

    if args.weasel:
        print("\nstaging into the Weasel fork:")
        stage_weasel(args.version, Path(args.weasel).expanduser().resolve())
        print("\n  now, on Windows, in that directory:")
        print("    build.bat installer")
        print("  which writes output/archives/weasel-<version>-installer.exe")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
